### PR TITLE
Sinequa api notebook

### LINKED ISSUE #1: Define initial search engine requirements
## 💡 Description

Define and prioritize requirements for the search engine and what we want the service to accomplish. These can be either a formal requirements doc or user stories.

Some initial thoughts:

* Search archive data (registry)
* Search archive documentation
* Search PDS online documentation (website content)
* Search by synonymous terms
* Search by features (e.g. Olympus Mons)
* Search other planetary data systems (e.g. IVOA)
* Machine-learning / training?

### LINKED ISSUE #2: Evaluate SDE, Legacy Registry, and OpenSearch Keyword Search capabilities
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data user

### 💪 Motivation

...so that I can search for data by domain or context.  I will be able to search for features of a target to find all relevant data.

### 📖 Additional Details

We are investigating the existing search capability established by the NASA Science Mission Directorate (SMD) Science Discovery Engine (SDE) as a baseline for this: https://sciencediscoveryengine.nasa.gov/app/nasa-sba-smd/#/home.  In particular the Sinequa service provides the backend search capability for SDE.  They support standard keyword search and a deeper search capability called "neural search" that applies Natural Language Processing (NLP) technology.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect** 

### ⚙️ Engineering Details

_No response_

### PR DESCRIPTION
**Pull request by jjacob7734**
## 🗒️ Summary
Created new Jupyter notebook demonstrating how to use the Sinequa REST API for the following functionality:
* Basic search
* Pagination
* Sorting
* Filtering by tab
* Filtering by Facet

## ⚙️ Test Data and/or Report
The new Jupyter notebook is added to the repo in expanded form with all cells run successfully. 

## ♻️ Related Issues

Resolves: https://app.zenhub.com/workspaces/portfolio-backlog-5c87e859b7a0872dd10b87c5/issues/gh/nasa-pds/planetary-data-engine/8

### CODE REVIEW

**Review by tloubrieu-jpl — CHANGES_REQUESTED** [review]
Hi @jjacob7734 , could you update the README.md to have the instructions to start and run the notebook,and the setup.cfg  to have the dependency needed.

In the readme we expect the minimal instruction, e.g.:
 
    pip install -e .
    jupyter-lab

Thanks !

**Comment by jjacob7734** [comment]
@tloubrieu-jpl I added a `README.md` based on what we did for the search API notebooks repo and a `requirements.txt`.  I tested the installation with the `requirements.txt` on my laptop and it works for me.  Please take a look.

**Comment by jjacob7734** [comment]
@tloubrieu-jpl The merging is blocked due to a CI/CD error that @jordanpadams and @nutjob4life will be fixing:  https://github.com/NASA-PDS/planetary-data-engine/issues/13

**Comment by jordanpadams** [comment]
@nutjob4life can you take a look at this when you have a chance?

**Comment by nutjob4life** [comment]
[I thought I already addressed this](https://github.com/NASA-PDS/planetary-data-engine/issues/13#issuecomment-1771814241)? Did I miss something else?

**Comment by nutjob4life** [comment]
@jordanpadams @tloubrieu-jpl @jjacob7734 added version pins in https://github.com/NASA-PDS/planetary-data-engine/commit/e271ffd1e18b9cb394a5c5453621d6107c8991fd

**Comment by jjacob7734** [comment]
> @jordanpadams @tloubrieu-jpl @jjacob7734 added version pins in [e271ffd](https://github.com/NASA-PDS/planetary-data-engine/commit/e271ffd1e18b9cb394a5c5453621d6107c8991fd)

Thanks, @nutjob4life .  Looks like the checks pass now.  @tloubrieu-jpl would you like to review and do the merge?

**Review by tloubrieu-jpl — APPROVED** [review]

**Pull request merged**
